// Code generated by schema-generate. DO NOT EDIT.

package messages

import "time"

// AppInfo
type AppInfo struct {
  Active bool `json:"active,omitempty"`
  Daemon string `json:"daemon,omitempty"`
  Enabled bool `json:"enabled,omitempty"`
  Name string `json:"name,omitempty"`
}

// AppsRequest
type AppsRequest struct {
  Action string `json:"action,omitempty"`
  Names []string `json:"names,omitempty"`
}

// AppsResponse
type AppsResponse struct {
  ChangeId string `json:"changeId,omitempty"`
  Error string `json:"error,omitempty"`
}

// AssertionsRequest
type AssertionsRequest struct {
  Type string `json:"type,omitempty"`
}

// AssertionsResponse
type AssertionsResponse struct {
  Stream string `json:"stream,omitempty"`
}

// AsyncResponse
type AsyncResponse struct {
  ChangeId string `json:"changeId,omitempty"`
  Error string `json:"error,omitempty"`
}

// ErrorInfo
type ErrorInfo struct {
  Message string `json:"message,omitempty"`
}

// MqttConnectionStatus
type MqttConnectionStatus struct {
  Connected bool `json:"connected"`
  ErrorInfo *ErrorInfo `json:"errorInfo,omitempty"`
}

// MqttConnectionStatusRequest
type MqttConnectionStatusRequest struct {
}

// Snap
type Snap struct {
  Apps []*AppInfo `json:"apps,omitempty"`
  Channel string `json:"channel,omitempty"`
  Id string `json:"id,omitempty"`
  InstallDate time.Time `json:"installDate,omitempty"`
  InstalledSize int64 `json:"installedSize,omitempty"`
  Name string `json:"name,omitempty"`
  Revision string `json:"revision,omitempty"`
  Status string `json:"status,omitempty"`
  Title string `json:"title,omitempty"`
  TrackingChannel string `json:"trackingChannel,omitempty"`
  Type string `json:"type,omitempty"`
  Version string `json:"version,omitempty"`
}

// SnapsResponse
type SnapsResponse struct {
  Snaps []*Snap `json:"snaps,omitempty"`
}

// SnapsSnapRequest
type SnapsSnapRequest struct {
  Action string `json:"action,omitempty"`
  Channel string `json:"channel,omitempty"`
}
