name: iot-agent
version: "0.4"
summary: IoT Device Management Agent using MQTT
description: |
  The IoT Agent enrolls a device with the IoT Identity service and receives credentials to access the MQTT broker.
  Via MQTT, it establishes communication with an IoT Management service, so the device can be remotely monitored and managed over a
  secure connection.

  The agent is intended to operate on a device running Ubuntu or Ubuntu Core with snapd enabled.
  The device management features are implemented using the snapd REST API.
confinement: strict
grade: stable
base: core18

apps:
  agent:
    command: bin/launch_agent
    daemon: simple
    plugs:
      - network
      - network-bind
      - snapd-control    # it needs these privileged interfaces
      - shutdown         # but they trigger a manual store review
  unregister:
    command: bin/unregister

parts:
  src:
    plugin: dump
    source: src

  client:
    plugin: nil
    source: .
    build-snaps:
      - go/1.16/stable
      - task
    override-build: |
      export GOPATH="$(go env GOPATH)"
      export PATH="$PATH:$GOPATH/bin"
      mkdir -p "$SNAPCRAFT_PART_INSTALL"/bin
      go get -u github.com/everactive/generate/...
      go build -o agent bin/agent/main.go
      go build -o configure bin/configure/main.go
      mv agent "$SNAPCRAFT_PART_INSTALL"/bin
      mv configure "$SNAPCRAFT_PART_INSTALL"/bin
    stage:
      - bin/agent
      - bin/configure
    build-packages:
      - git
      - gcc
